services:
  app:
    image: docker.io/jc21/nginx-proxy-manager:latest
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
      - DB_POSTGRES_HOST=db
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USER=npm
      - DB_POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRES_NAME=npm
      - DISABLE_IPV6=true
    ports:
      - 30020:80
      - 30021:81
      - 30022:443
    volumes:
      - /mnt/work/apps/nginx-proxy-manager/data:/data
      - /mnt/work/apps/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: npm
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: npm
    volumes:
      - /mnt/work/apps/nginx-proxy-manager/postgres:/var/lib/postgresql/data
