---
repositories:
  - name: k3rnelpan1c-helm-charts
    url: https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/

releases:
  - name: uptime-kuma
    namespace: monitoring
    createNamespace: true
    chart: k3rnelpan1c-helm-charts/uptime-kuma
    version: 1.5.0
    values:
      - values.yaml
