---
# image:
#   tag: 2.0.2

# persistence:
#   enabled: false
#   claimNameOverwrite: ""
#   sizeLimit: 4Gi
#   storageClass: ""
#   annotations: {}
#   labels: {}

# serviceMonitor:
#   enabled: false
#   authentication:
#     enabled: true
#     username: <username>
#     password: <token>
#     existingSecret: ""
#     existingSecretUsernameKey: username
#     existingSecretPasswordKey: token

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: status.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - status.home.arpa
      secretName: uptime-kuma-mkcert-tls
