env:
  - name: TZ
    value: Europe/Paris

persistence:
  enabled: true
  existingClaim: pvc-jellyseerr

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: jellyseerr.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - host:
        - jellyseerr.home.arpa
      secretName: jellyseerr-mkcert-tls
