env:
  - name: TZ
    value: Europe/Paris

persistence:
  enabled: true
  existingClaim: pvc-jellyseerr

secretName: jellyseerr-tls
ingress:
  enabled: true
  className: traefik
  annotations: []
  hosts:
    - host: jellyseerr.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - host: jellyseerr.home.arpa
      paths:
        - path: /
          pathType: Prefix

