services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 20080:80/tcp
      - 20443:443/tcp
    environment:
      TZ: Europe/Paris
      FTLCONF_webserver_api_password: ${PIHOLE_API_PASSWORD}
      FTLCONF_dns_listeningMode: all
    volumes:
      - /mnt/work/apps/pi-hole/etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
