apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyseerr
spec:
  storageClassName: zfs-vm-pool-jellyseerr
  capacity: 
    storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/jellyseerr
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyseerr
  namespace: media-center
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-vm-pool-jellyseerr

