apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bazarr-media
spec:
  storageClassName: zfs-tank-bazarr
  capacity: 
    storage: 25Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bazarr-config
spec:
  storageClassName: zfs-vm-pool-bazarr-config
  capacity: 
    storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/bazarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]

