---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarr-media
spec:
  storageClassName: zfs-tank-sonarr
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarr-config
spec:
  storageClassName: zfs-vm-pool-sonarr-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/sonarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
