---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prowlarr-config
spec:
  storageClassName: zfs-vm-pool-prowlarr-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/prowlarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
