---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qbittorrent-vpn-config
spec:
  storageClassName: zfs-vm-pool-qbittorrent-vpn
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/qbittorrent-vpn/qbittorrent
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qbittorrent-vpn-gluetun
spec:
  storageClassName: zfs-vm-pool-qbittorrent-vpn
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/qbittorrent-vpn/gluetun
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qbittorrent-vpn-downloads
spec:
  storageClassName: zfs-tank-qbittorrent-vpn
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
