apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn-proton
  namespace: qbittorrent-vpn
type: Opaque
stringData:
  username: ref+file://_secret.yaml#/qbittorrent/username
  password: ref+file://_secret.yaml#/qbittorrent/password
