services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
    ports:
      - "3001:3001"
    volumes:
      - /mnt/work/apps/uptime-kuma/data:/app/data
    restart: unless-stopped
