{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dozzle.fullname" . }}
  labels:
    {{- include "dozzle.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dozzle.fullname" . }}
  labels:
    {{- include "dozzle.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dozzle.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "dozzle.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
