---
services:
  caddy:
    image: caddy:2.11
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-logs:/var/log/caddy
      - caddy-data:/data
      - caddy-config:/config
    # environment:
    #   - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - frps

  frps:
    build:
      context: .
      dockerfile: Dockerfile.frps
    restart: unless-stopped
    ports:
      - 7000:7000
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro
    command:
      - -c
      - /etc/frp/frps.toml

volumes:
  caddy-data:
  caddy-config:
  caddy-logs:
