---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cnpg
spec:
  storageClassName: zfs-vm-pool-cnpg
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/cnpg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
