---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-admin_db-secret
  namespace: cnpg-database
type: Opaque
stringData:
  username: ref+file://_secret.yaml#/cloudnative-pg/username
  password: ref+file://_secret.yaml#/cloudnative-pg/password
