---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vibe-kanban
spec:
  storageClassName: zfs-vm-pool-vibe-kanban
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/vibe-kanban
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
