---
nameOverride: stirling-pdf
ingressClassName: traefik
ingress:
  enabled: true
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - name: stirling-pdf.home.arpa
      path: /
      tls: false
    - name: stirling-pdf.home.arpa
      path: /
      tls: true
      tlsSecret: stirling-pdf-mkcert-tls
