services:
  app:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - "30020:80"
      - "30021:81"
      - "30022:443"
    volumes:
      - /mnt/work/apps/nginx-proxy-manager/data:/data
      - /mnt/work/apps/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
