services:
  app:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /mnt/work/apps/nginx-proxy-manager/data:/data
      - /mnt/work/apps/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    network_mode: host
