---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
type: Opaque
stringData:
  username: ref+file://_secret.yaml#/kube-prometheus-stack/grafana/admin/username
  password: ref+file://_secret.yaml#/kube-prometheus-stack/grafana/admin/password
