env:
  TZ: Europe/Paris

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    readOnly: false
    storageClass: zfs-vm-pool-bazarr-config
  media:
    enabled: false
    type: pvc
    mountPath: /
    readOnly: false
    storageClass: zfs-tank-bazarr
    accessMode: ReadWriteOnce
    size: 25Gi

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: mkcert-ca
    labels: {}
    ingressClassName: traefik
    hosts:
      - host: bazarr.home.arpa
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - bazarr.home.arpa
        secretName: bazarr-mkcert-tls
