apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-media
spec:
  storageClassName: zfs-tank-jellyfin
  capacity: 
    storage: 25Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-config
spec:
  storageClassName: zfs-vm-pool-jellyfin-config
  capacity: 
    storage: 5Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/jellyfin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-cache
spec:
  storageClassName: zfs-vm-pool-jellyfin-cache
  capacity: 
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /vm-pool/jellyfin/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["joi"]


